# Generated by Django 3.2.7 on 2021-09-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_alter_profile_dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500)),
                ('cover', models.ImageField(blank=True, upload_to='board_covers/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subscriberCount', models.IntegerField(default=0)),
                ('admins', models.ManyToManyField(related_name='inspected_boards', to=settings.AUTH_USER_MODEL)),
                ('banned_users', models.ManyToManyField(related_name='forbidden_boards', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='subscribed_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
