# Generated by Django 3.2.7 on 2021-09-26 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_auto_20210926_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='efficientMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='efficientMode',
            field=models.BooleanField(default=False),
        ),
    ]
