# Generated by Django 3.2.7 on 2021-09-27 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0010_alter_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='inspected_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='forbidden_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
