# Generated by Django 3.2.7 on 2021-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20210927_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
