# Generated by Django 3.2.7 on 2021-10-05 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0015_alter_comment_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='Circle', max_length=64)),
                ('topType', models.CharField(default='', max_length=64)),
                ('accessoriesType', models.CharField(default='', max_length=64)),
                ('hairColor', models.CharField(default='', max_length=64)),
                ('facialHairType', models.CharField(default='', max_length=64)),
                ('facialHairColor', models.CharField(default='', max_length=64)),
                ('clotheType', models.CharField(default='', max_length=64)),
                ('clotheColor', models.CharField(default='', max_length=64)),
                ('graphicType', models.CharField(default='', max_length=64)),
                ('eyeType', models.CharField(default='', max_length=64)),
                ('eyebrowType', models.CharField(default='', max_length=64)),
                ('mouthType', models.CharField(default='', max_length=64)),
                ('skinColor', models.CharField(default='', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
