# Generated by Django 3.2.8 on 2021-10-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20211006_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('q', 'q'), ('t', 't'), ('v', 'v'), ('i', 'i'), ('l', 'l')], default='t', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_posts', to='forum.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_posts', to='forum.Profile'),
        ),
    ]
