# Generated by Django 3.2.8 on 2021-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20211007_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='inspected_boards', to='forum.Profile'),
        ),
        migrations.AlterField(
            model_name='board',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='forbidden_boards', to='forum.Profile'),
        ),
        migrations.AlterField(
            model_name='board',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_boards', to='forum.Profile'),
        ),
    ]
