# Generated by Django 3.2.8 on 2021-10-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20211009_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
    ]
