# Generated by Django 3.2.8 on 2021-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_post_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='correctOption',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
