# Generated by Django 3.2.8 on 2021-10-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_post_correctoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cover',
        ),
        migrations.AddField(
            model_name='board',
            name='icon',
            field=models.URLField(blank=True, default=''),
        ),
    ]
