# Generated by Django 3.2.8 on 2021-10-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20211012_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='icon',
            field=models.URLField(blank=True, default='https://storage.googleapis.com/learnitbucket/forum/uploads/emblem.jpg'),
        ),
    ]
