# Generated by Django 3.2.8 on 2021-10-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_alter_board_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pollResultOptionA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pollResultOptionB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pollResultOptionC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pollResultOptionD',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('q', 'q'), ('t', 't'), ('v', 'v'), ('i', 'i'), ('l', 'l'), ('f', 'f'), ('p', 'p')], default='t', max_length=1),
        ),
    ]
