# Generated by Django 3.2.8 on 2021-10-27 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_auto_20211021_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('commented', 'commented on your post'), ('replied', 'replied to your comment')], default='Comment on Subject', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_acts', to='forum.profile')),
                ('Object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_notif', to='forum.post')),
                ('Target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_notif', to='forum.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
